ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 15

#enemy constants
SPAWN_COOLDOWN = 400
ENEMY_FRAMES = 24

#turret constants
TURRET_LEVELS = 3
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 1
ANIMATION_DELAY = 15
DAMAGE = 5